version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres_mottu
    environment:
      POSTGRES_USER: mottu
      POSTGRES_PASSWORD: mottu
      POSTGRES_DB: mottu_rental
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_mottu
    ports:
      - "5672:5672"   
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  minio:
    image: minio/minio:latest
    container_name: minio_mottu
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin
    ports:
      - "9000:9000"  
      - "9001:9001"   
    volumes:
      - minio:/data

  mc: 
    image: minio/mc:latest
    container_name: minio_mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 5;
        mc alias set local http://minio:9000 admin adminadmin;
        mc mb local/uploads || true;
        mc anonymous set download local/uploads;
        exit 0;
      "

volumes:
  pgdata:
  minio:
